version: '3.8'

services:
  recrutement_app:
    build: .
    ports:
      - "4008:4008"  # Map container port 5000 to host port 5000
    environment:
      - DATABASE_URL=postgresql://jordan:Damas237@recrutement_postgres:5432/Base_donnee
    depends_on:
      - recrutement_postgres
    networks:
      - recrutement_network
    volumes:
      - ./app/static/uploads:/app/app/static/uploads

  recrutement_postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=Base_donnee
      - POSTGRES_USER=jordan
      - POSTGRES_PASSWORD=Damas237
    ports:
      - "4007:4006"  # Map container port 5432 to host port 5433 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recrutement_network

networks:
  recrutement_network:
    driver: bridge

volumes:
  postgres_data: