"""Initialisation des migrations

Revision ID: 4e1423204c92
Revises: 
Create Date: 2024-12-20 18:54:22.216868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1423204c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint('application_job_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('application_candidate_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'candidate', ['candidate_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=1235),
               type_=sa.String(length=154632),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=154632),
               type_=sa.VARCHAR(length=1235),
               existing_nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('application_candidate_id_fkey', 'candidate', ['candidate_id'], ['id'])
        batch_op.create_foreign_key('application_job_id_fkey', 'job', ['job_id'], ['id'])

    # ### end Alembic commands ###
